[tool.black]
line-length = 110
target_version = ['py35']
include = '\.pyi?$'
exclude = '''

(
  /(
    \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | migrations/*
)
'''
